### ISSUE TITLE
After successful payment, why do I receive two callbacks

### ISSUE THREAD

**Issue by justforjava** [stripe-samples/accept-a-card-payment#23]
After successful payment, why do I receive two callbacks,
One is charge.succeeded,
The other is payment_intent.succeeded.

**Comment by 326812416** [comment]
me too!

**Comment by 326812416** [comment]
This is my log, I don't know why there will be a payment and a charge.

ALL ACTIVITY

The payment pi_1GY6Y8GLe5Y6mXp1VLPAUPcf for $150.00 USD has succeeded
4/15/20, 4:24:50 PM

ch_1GY6YAGLe5Y6mXp1rV7VShDe was charged $150.00 USD
4/15/20, 4:24:50 PM

PaymentIntent status:
succeeded
200 OK

A request to confirm a PaymentIntent pi_1GY6Y8GLe5Y6mXp1VLPAUPcf completed
4/15/20, 4:24:49 PM

A new payment pi_1GY6Y8GLe5Y6mXp1VLPAUPcf for $150.00 USD was created
4/15/20, 4:24:48 PM

PaymentIntent status:
requires_payment_method
200 OK

A request to create a PaymentIntent completed
4/15/20, 4:24:48 PM

**Comment by thorsten-stripe** [comment]
That is expected, the PaymentIntent creates a charge for you, see https://stripe.com/docs/payments/payment-intents/verifying-status for details.

When using PaymentIntents it is sufficient to handle the `payment_intent.succeeded` event, which will fire for all payment methods.

**Comment by 326812416** [comment]
I don't know why I still receive the charge message, what does this message mean?

**Comment by thorsten-stripe** [comment]
The PaymentIntent is not a payment but rather it creates a charge for you. When the charge is succeeded the PaymentIntent will update to succeeded. That's why you receive both events.

Please only file issues here that you believe represent actual bugs or feature requests for this sample.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.
